version: "3.4"

services:

    apache_nrdr:
        build: ./build/apache-php
        container_name: ncrnadatabases_webserver
        restart: always
        volumes:
            - ./volumes/frontend:/var/www/html
        depends_on:
             - db_nrdr
        networks:
            - webserver
            - db

    db_nrdr:
        build: ./build/db
        container_name: nrdr_db
        restart: always
        volumes:
            - ./volumes/db:/var/lib/mysql
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=YES
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASS}
        networks:
             - db

networks:
    db:
    webserver:
