var word_list = [
    {text: "structure", weight: 9, html: {"class": "vertical"}},
    {text: "antisense", weight: 8},
    {text: "bioinformatics", weight: 12},
    {text: "regulation", weight: 8},
    {text: "diseases", weight: 8},
    {text: "RNA", weight: 14},
    {text: "biology", weight: 7},
    {text: "epigenetics", weight: 8, html: {"class": "vertical"}},
    {text: "chromatin", weight: 8},
    {text: "cancer", weight: 9},
    {text: "binding", weight: 8},
    {text: "target", weight: 8},
    {text: "informatics", weight: 8},
    {text: "PCR", weight: 8},
    {text: "non-conding", weight: 14},
    {text: "intergenic", weight: 6},
    {text: "expression", weight: 8, html: {"class": "vertical"}},
    {text: "NGS", weight: 8},
    {text: "gene", weight: 8},
    {text: "tools", weight: 9},
    {text: "cells", weight: 7},
    {text: "networks", weight: 7},
    {text: "transcription", weight: 9, html: {"class": "vertical"}},
    {text: "databases", weight: 13, html: {"class": "vertical"}},
    {text: "tissues", weight: 12},
    {text: "northern", weight: 9},
    {text: "immunoprecipitation", weight: 10},
    {text: "lung", weight: 9},
    {text: "microarray", weight: 10}
];